version: '3.9'

services:
  mongo-db-bitcoin-candle:
    image: mongo:latest
    container_name: mongo-db-bitcoin-candle
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
  
volumes:
  mongodb_data_container:
